version: "3"
services:
  app:
    container_name: conta-app
    build: .
    ports:
      - "49160:8080"
    network_mode: "bridge"

  mongo:
    container_name: conta-mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    network_mode: "bridge"
